### ISSUE TITLE
[scg] XRRGetCrtcInfo call is not needed, can be removed

### ISSUE THREAD

**Issue by temporaryrespite** [jumper149/blugon#10]
Unless I'm missing something, the call for [`XRRGetCrtcInfo`](https://cgit.freedesktop.org/xorg/lib/libXrandr/tree/src/XrrCrtc.c#n37) does nothing and can be removed (tested):
https://github.com/jumper149/blugon/blob/44b908ef126660800671f90557f3dee342105e7e/backends/scg/scg.c#L32

**Comment by jumper149** [comment]
Simple one, but I guess you are right. Thank you :)

I will check everything before PRing.
