### ISSUE TITLE
Issues with installing blugon

### ISSUE THREAD

**Issue by mqbpjfg2** [jumper149/blugon#21]
Hi,

I had blugon intalled and working fine on linux mint but after re-installing my linux mint I don't seem to be able to install blugon again. 
Here is the error I get:
```
~/blugon$ make
sed "s|MAKE_INSTALL_PREFIX = '.*'|MAKE_INSTALL_PREFIX = '/usr'|g" blugon.py > blugon
sed "s|MAKE_INSTALL_PREFIX|/usr|g" systemd/user/blugon.service > blugon.service
gzip --best --force --keep blugon.1
cd backends/scg && make build
make[1]: Entering directory '/home/flo/blugon/backends/scg'
gcc -O2 -std=c11 -D_POSIX_C_SOURCE=200809L -Wall -Wextra -Wpedantic -I/usr/X11R6/include -L/usr/X11R6/lib -lX11 -lXrandr -o scg scg.c
scg.c:1:10: fatal error: errno.h: No such file or directory
 #include <errno.h>
          ^~~~~~~~~
compilation terminated.
Makefile:7: recipe for target 'build' failed
make[1]: *** [build] Error 1
make[1]: Leaving directory '/home/flo/blugon/backends/scg'
Makefile:5: recipe for target 'build' failed
make: *** [build] Error 2
```
I have tried with a older release (1.11.4) but I get the same mistake... I'm quite puzzled because it was working just fine before...
Any idea what I could try?

Thank you!

**Comment by jumper149** [comment]
`errno.h` is part of the C Standard Library.

I am not familiar with Linux Mint's package repository, but Archlinux and nixpkgs call the package `glibc`.
I hope you can find what you are missing!

You could also use nix to install blugon, but that really shouldnt be necessary when you fix your dependencies.

**Comment by mqbpjfg2** [comment]
Thank you very much for your answer!
I managed to get it working installing build-essential and using the release 1.11.4 (I had issues with the location of libraries X11R6 with the newest version).
But it's up and running now :)
Thanks for your help!
