### ISSUE TITLE
How to check if blugon light-filter is running?

### ISSUE THREAD

**Issue by Matipa00** [jumper149/blugon#27]
I'm trying to make a script that turns on and off blugon, and for that I need to check whether the light-filter is applied or not. Problem is, blugon's process is already dead milisecond later is executed, so there's no process to check. There is other method to tell the filter is up? I'm using the svg backend, and started blugon with an autostart.sh script

**Comment by jumper149** [comment]
I am guessing you are using the `--setcurrent` flag?
In that case every time it is applied, the value will be written to `~/.config/blugon/current`.

This way you should be able to get the timestamp of the last call with:

```
date -r ~/.config/blugon/current
```

**Comment by Matipa00** [comment]
I didn't know about that flag because it's not mentioned on the README, but as soon as I get my hands on my laptop again tomorrow I'm gonna include that on the autostart script. Thx for replying

**Comment by jumper149** [comment]
The Readme is a bit concise,
but the manpage should suffice.
