### ISSUE TITLE
"Failed to connect to bus" and "Failed to enable unit"

### ISSUE THREAD

**Issue by athyla** [jumper149/blugon#3]
Hello!

I am on Manjaro 18.1 and I have installed blugon from the Arch AUR.
When I try to enable the blugon service only for the user, I get the following:

`$ sudo systemctl --user enable blugon.service`
`Failed to connect to bus: No such file or directory`

When I try to enable blugon system-wide, I get the following:
`$ sudo systemctl enable blugon.service`
`Failed to enable unit: Unit file blugon.service does not exist.`

Please let me know what else do you need to investigate this issue.

Thanks!

**Comment by jumper149** [comment]
Run

    systemctl --user enable blugon.service

, but *not* as root! :)

**Comment by athyla** [comment]
:) Thanks, that works!

Oh man, I need to install “safe eyes” too, so it makes me take regular breaks from the computer... I am rooted in front of it, hahaha!

Cheers!
