### ISSUE TITLE
error with compiling of blugon.py 

### ISSUE THREAD

**Issue by astrosander** [jumper149/blugon#30]
When I try to run `blugon.py` the error appears
```
Traceback (most recent call last):
  File "C:\Users\astrosander\Desktop\blugon-1.12.1\blugon.py", line 43, in <module>
    CONFIG_DIR = getenv('HOME') + '/.config'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[Finished in 92ms]
```
How can I solve it
(Windows 11)

**Comment by jumper149** [comment]
Sorry, but blugon doesn't support Windows (and probably never will unless someone comes along and writes a backend for it).

With blugon I mainly wanted to follow POSIX principles and Windows is just very different in that sense.

**Comment by astrosander** [comment]
Ok, thanks
