### ISSUE TITLE
Compatibility with xscreensaver

### ISSUE THREAD

**Issue by damscal** [jumper149/blugon#4]
At present and with default config, xscreensaver disables blugon when a screensaver is activated. Is there a way to have blugon run on top of screensavers?

**Comment by jumper149** [comment]
I tried `xscreensaver` and previewed some screensavers and didn't notice anything bad.

**Comment by yosh-se** [comment]
I think it behaves badly with dpms. I use xscreensaver, but only for blanking my screens and putting them into powersave. IIRC the screen resets to default settings when it powers back up. Haven't tested/verified that any of this is 100%

**Comment by jumper149** [comment]
I really have no idea how I could fix that with blugon, but you can maybe run `blugon --once` from a script if the reset comes consistently with a specific event.

**Comment by damscal** [comment]
Actually it works fine with dpms or when previewing screensavers, the issue is when screensavers actually get triggered.
Steps to reproduce:
Run ``

**Comment by howaboutsynergy** [comment]
I run `blugon --once` only and see no resets with xfce4-screensaver (when it triggers itself, I don't have that `-demo` one though), on ArchLinux. I've also tried dpms-ing manually even, and still no resets, the color temperature is kept.

```
sleep 1
xset dpms force suspend
sleep 1
xset dpms force off
sleep 1
xset dpms force standby
setterm --blank force
```

Now I notice that I've no brightness reduction setting(it's set to Never) so maybe this is why?
![Screenshot_2019-10-04_14-38-22](https://user-images.githubusercontent.com/49106389/66208102-a4821100-e6b4-11e9-9364-146e65e28edb.png)

**Comment by howaboutsynergy** [comment]
oh wait, my bad `xfce4-screensaver` is not `xscreensaver`. I've no idea why I equated the two.

**Comment by damscal** [comment]
xscreensaver is another package, not included in xfce

**Comment by howaboutsynergy** [comment]
Is the `Install Colormap` from `Advanced` tab inside `xscreensaver-demo` selected and selectable? it's disabled for me. I think this is why I can't reproduce the reset(s) with [these](https://github.com/jumper149/blugon/issues/4#issuecomment-538376930) steps, thus the color temperature is kept.

**Comment by damscal** [comment]
@howaboutsenergy Good one. It is enabled and unselectable for me. I will look into a way to disable it and see if that solves the issue.

**Comment by howaboutsynergy** [comment]
> @howaboutsenergy Good one. It is enabled and unselectable for me. I will look into a way to disable it and see if that solves the issue.

Ah, I'm afraid it's always unselectable if you have 16+bit colors and thus not in effect :(
```
This does nothing if you have a TrueColor  (16-bit  or  deeper)
               display.  (Which, in this century, you do.)
```

It's probably not the cause, sadly. But you can change it in `~/.xscreensaver`
`installColormap:    True`, not sure how to restart xscreensaver afterwards though, except from `xscreensaver-demo`

**Comment by damscal** [comment]
I've pinpointed the issue. It is caused  by the Fade to Black advanced option of xscreensaver. Disabling it solves the problem. I'm closing the issue. Thanks for the support!
