### ISSUE TITLE
exit code 11 aka (silent)segfault when backend scg is used on tty, or DISPLAY isn't set on X

### ISSUE THREAD

**Issue by temporaryrespite** [jumper149/blugon#9]
Because `dpy` here[1] will be null when running eg. `blugon -b scg -r -o`:
[1] https://github.com/jumper149/blugon/blob/44b908ef126660800671f90557f3dee342105e7e/backends/scg/scg.c#L10

and there's no check & graceful exit.
The exit code for the above command is `11`, but when running `scg` backend directly, on tty(rather than inside X), the segfault can be seen, eg.:
`/lib/blugon/scg 1.0 0.6949030005552019 0.4310480202110507`
```
$ /lib/blugon/scg 1.0 0.6949030005552019 0.4310480202110507
[ 1627.389262] scg[93373]: segfault at e0 ip 000055e14ea4d0dd sp 00007ffca8ec6e00 error 4 in scg[55e14ea4d000+1000]
[ 1627.390830] Code: 00 00 00 00 00 00 00 00 00 00 00 00 00 41 57 41 56 41 55 49 89 f5 41 54 55 89 fd 31 ff 53 48 83 ec 28 e8 a6 ff ff ff 48 89 c3 <48> 63 80 e0 00 00 00 48 89 df 48 c1 e0 07 48 03 83 e8 00 00 00 48
[ 1627.392435] potentially unexpected fatal signal 11.
[ 1627.394046] CPU: 1 PID: 93373 Comm: scg Kdump: loaded Tainted: G          I       5.4.10-g7a02c193298e #46

[ 1627.397178] RIP: 0033:0x55e14ea4d0dd
[ 1627.398696] Code: 00 00 00 00 00 00 00 00 00 00 00 00 00 41 57 41 56 41 55 49 89 f5 41 54 55 89 fd 31 ff 53 48 83 ec 28 e8 a6 ff ff ff 48 89 c3 <48> 63 80 e0 00 00 00 48 89 df 48 c1 e0 07 48 03 83 e8 00 00 00 48
[ 1627.400266] RSP: 002b:00007ffca8ec6e00 EFLAGS: 00010202
[ 1627.401848] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000090
[ 1627.403418] RDX: 0000000000000080 RSI: 00007ffca8ec6f48 RDI: 00007ff2eb6f5090
[ 1627.404968] RBP: 0000000000000004 R08: 0000000000000000 R09: 0000000000000000
[ 1627.406527] R10: 000055e14ea4c52c R11: 00007ff2eb680840 R12: 000055e14ea4d280
[ 1627.408031] R13: 00007ffca8ec6f48 R14: 0000000000000000 R15: 0000000000000000
[ 1627.409483] FS:  00007ff2eb414d80 GS:  0000000000000000
[ 1627.423791] systemd[1]: Started Process Core Dump (PID 93385/UID 0).
Segmentation fault (core dumped)
[ 1627.938066] systemd-coredump[93393]: Process 93373 (scg) of user 1000 dumped core.
[ 1627.938066]
[ 1627.938066] Stack trace of thread 93373:
[ 1627.938066] #0  0x000055e14ea4d0dd main (scg + 0x10dd)
[ 1627.938066] #1  0x00007ff2eb49e1b6 __libc_start_main (libc.so.6 + 0x271b6)
[ 1627.938066] #2  0x000055e14ea4d2ae _start (scg + 0x12ae)
[ 1627.938066]
[ 1627.948951] systemd[1]: systemd-coredump@2-93385-0.service: Succeeded.
```

or this can also reproduce it:
```bash
$ DISPLAY= /lib/blugon/scg 1.0 0.6949030005552019 0.4310480202110507
Segmentation fault (core dumped)

$ DISPLAY= blugon -b scg -r -o; echo "exit code:$?"
exit code:11
```

I didn't want to make a PR for this because i don't know how you want this handled (if ever), but the idea is something like this:
```c
///...
#include <stdio.h>      /* fprintf */
///...
  Display *dpy = XOpenDisplay(NULL);
  //If XOpenDisplay does not succeed, it returns NULL.
  if (NULL == dpy) {
    fprintf(stderr, "X is not running? or cannot open a connection to it. Is DISPLAY env var set?\n");
    return 1; // exit code 1
  }
```

**Comment by jumper149** [comment]
You are right, that the pointer `dpy` should be checked, if `NULL`.

When I wrote it I just used [blugon.py](https://github.com/jumper149/blugon/blob/44b908ef126660800671f90557f3dee342105e7e/blugon.py) to handle the segfault.

The `exit(11)` in [blugon.py](https://github.com/jumper149/blugon/blob/44b908ef126660800671f90557f3dee342105e7e/blugon.py) is being executed just when `DISPLAY` is empty and this should occur together with `XOpenDisplay(NULL);` returning a `NULL`-pointer.

Still, if anyone is interested in running just `scg`, it will be nicer to avoid the segfault! I will write PR for this soon and link it here.

Thank you for spotting this :)

**Comment by temporaryrespite** [comment]
> The `exit(11)` in [blugon.py](https://github.com/jumper149/blugon/blob/44b908ef126660800671f90557f3dee342105e7e/blugon.py) is being executed just when `DISPLAY` is empty

Thank you for [this](https://github.com/jumper149/blugon/blob/44b908ef126660800671f90557f3dee342105e7e/blugon.py#L481-L486) info. When I created this issue, I didn't realize this is what was happening, but instead, without looking into it, I assumed that somehow `python` was catching the segfault and preventing it from occurring(such as being reported by systemd on `dmesg`) and instead was just simply exiting with exit code 11. The assumption was based on my experience with something(can't remember what? glib2?) running tests and preventing the segfaults from reaching dmesg, so I knew that it was possible.

**Comment by jumper149** [comment]
This is all as expected :)

When merged segfaults should be avoided.
Thank you for investigating the issue :+1:
